### PR TITLE
fix: fix sonar issues

### PR DESCRIPTION
**Pull request by Naman0133**
Issue: [#440](https://github.com/sirixdb/sirix/issues/440)

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Can you format your changes with the SirixDB formatter?

**Comment by Naman0133** [comment]
yess sure

**Comment by Naman0133** [comment]
> Can you format your changes with the SirixDB formatter?

I am seeing all checks are passing, can you tell me is formatter needed ? if yes then how to do?

**Comment by JohannesLichtenberger** [comment]
There's a SirixDB.xml formatter you can import in Eclipse or IntelliJ.

**Comment by Naman0133** [comment]
> There's a SirixDB.xml formatter you can import in Eclipse or IntelliJ.

ohh okay will try and update the code

**Comment by Naman0133** [comment]
> There's a SirixDB.xml formatter you can import in Eclipse or IntelliJ.

Done, can you please review it now?
Thanks :)

**Comment by Naman0133** [comment]
@JohannesLichtenberger Please add the [hacktoberfest-accepted](https://github.com/sirixdb/sirix/labels/hacktoberfest-accepted) label

**Pull request merged**
