### PR TITLE
Issue#523: Refactor XML and JSON handling in CRUD operations

### PR DESCRIPTION
**Pull request by omkar-shitole**
# [WIP] Initial Refactoring of XML and JSON handling in CRUD operations

## Overview
This PR introduces to handle common logic for XML and JSON operations in the CRUD directory. The focus is on enhancing abstraction for create and delete operations, to reduce code duplication and improve maintainability.

## Changes
1. AbstractCreateHandler Enhancement:
   - Extended with implementing Common Method `createDatabaseIfNotExists()`
   - Refactored `XMLCreate` and `JsonCreate` to use this shared method.
 2. AbstractDeleteHandler Enhancement:
   - Extended with implementing Common Method `handle()`
   - Refactored `XMLDelete` and `JsonDelete` to use this shared method.
  
## Next Steps
- Review and refine current changes based on feedback
- Extend similar refactoring to other operations.
- Consider creating abstract base classes for classes which have almost similar methods and content.
   
## Review Request
Please focus on:
1. Effectiveness of the abstraction and adherence to "Template Method" design (Interface+Abstact+Implementations)
2. Potential issues with format-specific operations
3. Suggestions for further improvements or extensions of this refactoring approach

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Looking good :-)

**Comment by JohannesLichtenberger** [comment]
Are you going to add more stuff or should I already merge?

**Comment by omkar-shitole** [comment]
Thank you for your support. Definitely, I'll extend similar refactoring to other operations and commit the changes in the PR.

**Comment by omkar-shitole** [comment]
#Further Refactoring of XML and JSON Handling in CRUD Operations

## Overview
This PR continues the refactoring efforts to enhance XML and JSON handling within CRUD operations.

## Changes
1. **AbstractGetHandler Enhancement**:
   - Added common methods for data retrieval within `AbstractGetHandler`.
   - Refactored `JsonGet` and `XmlGet` to leverage these shared methods for centralized retrieval logic.

2. **AbstractUpdateHandler Introduction**:
   - Introduced `AbstractUpdateHandler` to manage update operations across both contexts.
   - Updated `JsonUpdate` and `XmlUpdate` to extend `AbstractUpdateHandler`, ensuring consistent update handling.

3. **Additional Refinements**:
   - Modified a few of the access modifiers to improve encapsulation.


## Next Steps
- Review and provide feedback on the newly implemented abstractions.
- Extend similar refactoring practices to other CRUD operations where applicable.
- Consider creating further abstract base classes for classes with similar methods and functionality.

## Review and Merge Request
Kindly review  changes.  I’ll continue contributing and working on other issues and  enhancements.

**Comment by JohannesLichtenberger** [comment]
Thanks a lot, I think it's great regarding clean code, but I'm on my phone, so I'll check tomorrow or later on :-) thanks a lot and as always I hope you'll contribute more ;) there's maybe room for a better Kotlin DSL API, maybe even a DSL to provide type safe and syntactically correct JSONiq. Other than that I'm currently working on reducing object allocations :-)

**Comment by JohannesLichtenberger** [comment]
Oh and maybe updating Vert.x to the newest version and check if we have to update anything.

**Pull request merged**
