### PR TITLE
[Vert.x upgrade #517] --fix

### PR DESCRIPTION
**Pull request by tsufiyan**
- Test cases passing
- Updated Vert.x to version 4.4.0
- Replaced deprecated methods with suitable ones.
- Defined vertxVersion property in gradle.properties for better control.

### CODE REVIEW

**Comment by tsufiyan** [comment]
Hi @JohannesLichtenberger
Please resolve conflicts and proceed

**Comment by JohannesLichtenberger** [comment]
Can you check what's now broken? Stupidly I merged the PR already, and the tests weren't executed again beforehand.

**Comment by JohannesLichtenberger** [comment]
Okay, one problem left at least: https://github.com/sirixdb/sirix/actions/runs/4570091024/jobs/8067029970

**Comment by tsufiyan** [comment]
Thanks for fix on several places. Now I will read about reordering handlers.
Thanks again...!

**Comment by JohannesLichtenberger** [comment]
Yes, but still  a test failure im the python client, sadly

**Comment by JohannesLichtenberger** [comment]
sirix-python-client/tests/test_sirix_sync.py::test_auth_refresh FAILED   [ 85%]

There's a NPE somewhere: s = 'Failure calling the RESTful API: java.lang.NullPointerException\n\tat java.base/java.util.Objects.requireNonNull(Obje....FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\n'
idx = 0

**Comment by tsufiyan** [comment]
lemme check that!

**Comment by JohannesLichtenberger** [comment]
Looking forward to your PR :-)

**Comment by tsufiyan** [comment]
PR raised, test passed, go ahead...

**Comment by JohannesLichtenberger** [comment]
Thanks, hope you'll continue to work on Sirix 👍

**Comment by tsufiyan** [comment]
Yep yep! I am currently working on reordering handlers.
ThanX

**Pull request merged**
