### PR TITLE
Gradle support #107

### PR DESCRIPTION
**Pull request by balajiv113**
The following are covered in comparison with maven,
**Modules**
- sirix-core
- sirix-examples
- sirix-xquery
- sirix-rest-api

**Plugins**

- gradle-release plugin as alternate for maven-release-plugin (Need verification)
- gradle-versions-plugin as alternate for maven-versions-plugin
- spotless-plugin-gradle as alternate for maven-license-plugin (need to run `gradlew spotlessApply` as spotlessCheck is failing currently)

**Plugins - Not Used**
- cobertura-maven-plugin
- maven-pmd-plugin
- maven-jxr-plugin

**Know differences**
- MANIFEST.MF contents will be different.
- pom.xml contents will be different 
- sirix-rest-api java doc will be empty

**Todo**

- Run `gradlew spotlessApply` and check in updated source
- Test the functionality of gradle-release-plugin
- Fix kotlin test cases without requiring server
- Generate kotlin javadoc once Dokka supports Java 13 (currently not supported).
- Update travis build
- Use gradle to generate and push docker image

**Command to run gradle build**
`gradle clean build (or) gradle build`

Note: 
1. I have verified that existing test cases are running without issues.
2. In sirix-rest-api module currently test-cases will not run as it is a kotlin based junit and it requires server running in localhost. Once its fixed in sirix-parent we can uncomment useJUnitPlatform()

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Hey, actually somehow the end-to-end tests in `sirix-rest-api` never ran automatically. It needs a fully configured Keycloak container starter and I'm always verifying it locally. But that's far from perfect. I think I can merge your stuff then, what do you think? :-)

**Comment by balajiv113** [comment]
Ya it can be merged. Once merged will work on todo that has been mentioned

**Comment by JohannesLichtenberger** [comment]
I'll test if I can release a new version on Maven tomorrow or on sunday, thanks a lot :-)

**Comment by JohannesLichtenberger** [comment]
Plus I'll look into this issue for setting up a running Keycloak container before running the end-to-end tests: https://github.com/sirixdb/sirix/issues/128

**Comment by balajiv113** [comment]
Ya that would be great. Gradle has docker plugin to run and stop a container. So if you already have some docker configuration that you use it to run keycloak then we can automate the starting of docker through gradle

**Comment by JohannesLichtenberger** [comment]
Yes, however I still have to add the user manually sadly. But using TestContainers as mentioned in the issue sounds good to me. One link in german: https://www.7p-group.com/blog/integrationstests-mit-testcontainers-spring-security-und-keycloak/

**Comment by balajiv113** [comment]
We can use the same logic as they have done in the example, in the example they have created a script to add a user in keycloak. I think that should be just fine for us also

**Comment by JohannesLichtenberger** [comment]
Yes, this one: https://github.com/cremich/testcontainers-keycloak/blob/master/src/test/resources/create-keycloak-user.sh for instance.

Roles are `create`, `view`, `update` and `delete` and realm is `sirix`.

**Comment by JohannesLichtenberger** [comment]
Do you know what this means?

2019-12-30T13:32:33.579+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':sirix-example:release'.
2019-12-30T13:32:33.579+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Included build C:\Users\Johannes\Documents\GitHub\sirix has build path :sirix which is the same as included build C:\Users\Johannes\Documents\GitHub\sirix

**Comment by balajiv113** [comment]
Not sure, am not getting that issue. Can you try stopping gradle daemons using 
`gradlew` --stop` and also by deleting .gradle folder

**Comment by JohannesLichtenberger** [comment]
I think it has to do with sub projects (BTW: only tried gradlew release):

https://github.com/gradle/gradle/blob/a452452ebfc67f1fb466ed51e2d593d6f3932f33/subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java#L245

**Comment by balajiv113** [comment]
Ya .. for me also the same issue is coming now. Am checking it will let update once i found a solution for this

**Comment by JohannesLichtenberger** [comment]
Ah, thanks for all your effort :-)

**Comment by balajiv113** [comment]
Looks like a limitation of the gradle-release-plugin itself.
In plugin [README](https://github.com/researchgate/gradle-release#multi-project-builds) also they have updated that multi-module projects are not fully supported.
We can run the commands like below,
gradlew :sirix-core:release
gradlew :sirix-example:release
gradlew :sirix-rest-api:release
gradlew :sirix-xquery:release

**Comment by JohannesLichtenberger** [comment]
Oh ok, will try

**Comment by JohannesLichtenberger** [comment]
For an "atomic" release I guess, I simply have to drop artifacts from the staging repo if one if these fails due to something.

**Comment by balajiv113** [comment]
Yes thats correct.

**Comment by balajiv113** [comment]
Kindly add the following line in root build.gradle file, 
release {
 failOnSnapshotDependencies = false
 tagTemplate = '$name-$version' //new line
}

I tried with this configuration, all the above mentioned commands worked except the sirix-xquery which fails in a junit test case due to a resource lock in sub-gradle process (in windows)

**Comment by JohannesLichtenberger** [comment]
will investigate

**Comment by JohannesLichtenberger** [comment]
Damn, I hate this build setup stuff.

```
johannes@johannesl3:~/sirixdb/sirix$ git fetch origin
johannes@johannesl3:~/sirixdb/sirix$ git reset --hard origin/master
HEAD is now at e80aa290 Update build.gradle to set tagTemplate for releases
johannes@johannesl3:~/sirixdb/sirix$ ./gradlew :sirix-core:release

> Task :sirix:sirix-core:confirmReleaseVersion

??> This release version: [0.9.4]  (WAITING FOR INPUT BELOW)
<=====--------> 38% EXECUTING [5s]

> Task :sirix:sirix:sirix-core:compileJava FAILED
> Task :sirix:sirix-core:runBuildTasks FAILED

> Task :sirix-core:release FAILED
Release process failed, reverting back any changes made by Release Plugin.
Running [git, checkout, gradle.properties] produced an error: [error: pathspec 'gradle.properties' did not match any file(s) known to git]
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sirix:sirix:sirix-core:compileJava'.
> Could not target platform: 'Java SE 13' using tool chain: 'JDK 11 (11)'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed
```

**Comment by JohannesLichtenberger** [comment]
And on my Windows Laptop, from which I'm usually releasing:

```
2019-12-30T18:35:54.315+0100 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on root.1
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':sirix:sirix-core:preTagCommit'.
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to push to remote - [To https://github.com/sirixdb/sirix.git
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   =       refs/heads/master:refs/heads/master     [up to date]
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Done
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ][fatal: AggregateException encountered.
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]      One or more errors occurred.
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ]
2019-12-30T18:35:54.315+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
2019-12-30T18:35:54.316+0100 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 4m 4s
```

**Comment by balajiv113** [comment]
Its your java version issue. Your pointing to Java 11, but build require Java 13

**Comment by JohannesLichtenberger** [comment]
I'm trying again on my Windows Laptop, where Java 13 is the only installed Java version :-) Removed the .gradle directory again... let's see. I think I didn't have everything from `origin`.

**Comment by JohannesLichtenberger** [comment]
Ah now, I'm getting the same error (without the Java 11 / Java 13 remark):

```
C:\Users\Johannes\Documents\GitHub\sirix>gradlew :sirix-core:release
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :sirix:sirix-core:confirmReleaseVersion

??> This release version: [0.9.4]  (WAITING FOR INPUT BELOW)
<=====--------> 38% EXECUTING [11s]

> Task :sirix:sirix:sirix-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :sirix:sirix:sirix-core:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :sirix:sirix-core:preTagCommit
Running [git, commit, -m, [Gradle Release Plugin] - pre tag commit:  'sirix-core-0.9.4'., -a] produced an error: []

> Task :sirix:sirix-core:preTagCommit FAILED

> Task :sirix-core:release FAILED
Release process failed, reverting back any changes made by Release Plugin.
Running [git, checkout, gradle.properties] produced an error: [error: pathspec 'gradle.properties' did not match any file(s) known to git.]
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.
Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sirix:sirix-core:preTagCommit'.
> Failed to push to remote - [To https://github.com/sirixdb/sirix.git
  =     refs/heads/master:refs/heads/master     [up to date]
  Done
  ][fatal: AggregateException encountered.
     One or more errors occurred.
  ]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 52s
1 actionable task: 1 executed
```

**Comment by JohannesLichtenberger** [comment]
Hm, the tag has been created before I think...

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @balajiv113 for code

**Pull request merged**
