### PR TITLE
Bumping vertx version to 4.0.0.Beta1

### PR DESCRIPTION
**Pull request by cunhazera**
Closes https://github.com/sirixdb/sirix/issues/297

### CODE REVIEW

**Comment by cunhazera** [comment]
@JohannesLichtenberger is there anything wrong with the build?

**Comment by mosheduminer** [comment]
I believe that various vertx APIs have changed between the 3.*.* versions and version 4.0.0, and the code would need to be upgraded to work with the new vertx APIs.

**Comment by JohannesLichtenberger** [comment]
Yes, exactly what @mosheduminer described.

**Comment by cunhazera** [comment]
My bad... I was trying to run without Java 14.

**Comment by cunhazera** [comment]
@JohannesLichtenberger @mosheduminer 
I'm getting this error at the github build: `Caused by: org.gradle.api.GradleException: This build must be run with Java 14`
But locally it fails at all integration tests `./gradlew clean build`
Any idea why?

**Comment by mosheduminer** [comment]
@cunhazera can you clarify what you mean by github build? The travis CI build fails on the integration tests as well, and is using Java 14.

**Comment by cunhazera** [comment]
It don't know much about gradle. Should I really change gradle/wrapper/gradle-wrapper.properties, build.gradle and gradle/wrapper/gradle-wrapper.properties files?

**Comment by mosheduminer** [comment]
It does seem that you introduced changes into build.gradle. I'm not sure why you added these, but it appears that you are targeting java 8, when the project can only be compiled with java 14. But I am not sure that actually causes the problem here.

(I only work on other sirixdb repositories, I probably know less about gradle than you do 😀, Johannes will probably have a better idea)

**Comment by cunhazera** [comment]
Maybe these changes were added by my intellij, idk. Let me remove that and see what happens.

**Comment by cunhazera** [comment]
Can you guys give me some help with this issue?

**Comment by mosheduminer** [comment]
I would guess that there is an authentication issue, which results in an error response, which results in the json errors.

**Pull request closed without merging**
