### PR TITLE
Javadoc fixes

### PR DESCRIPTION
**Pull request by punit-kulal**
List of the changes I have made:

- Removed &lt;h1&gt;Class Name/ Package Name&lt;/h1&gt; From all files
- Fixed incorrect parameter name in methods
- Corrected links to classes 
- Esacape special html characters

### CODE REVIEW

**Comment by punit-kulal** [comment]
Also a shorthand Guide while to avoid frequently repeated errors JavaDoc
- You need not write the name of the class in an h1 header or any header at all(throws Error)
-. Do not use <p> tag as a wrapper around other html entities, you can skip the <p> tag in such cases for formatting.
- escape special characters like 
	- &amp; → & (ampersand, U+0026)
	&lt; → < (less-than sign, U+003C)
	&gt; → > (greater-than sign, U+003E)
	&quot; → " (quotation mark, U+0022)
	&apos; → ' (apostrophe, U+0027)
- License or Declaration should be made with /* */ style comments and not /** */ Dangling comment

**Comment by JohannesLichtenberger** [comment]
Ah, thanks a lot. I can you merge my most recent changes in?

**Comment by punit-kulal** [comment]
> Ah, thanks a lot. Can you merge my most recent changes in?

Done

**Comment by JohannesLichtenberger** [comment]
Thanks a lot :+1: 

Feel free to contribute more if you like to :-)

**Pull request merged**
