### PR TITLE
Reduce cyclomatic complexity in service.json.serialize.StringValue.escape

### PR DESCRIPTION
**Pull request by EmilGedda**
Replace a switch with a HashMap and break out the specific unicode
escaping to a separate function. Fixes #16

### CODE REVIEW

**Comment by EmilGedda** [comment]
Sorry, was supposed to be a PR to a fork.
Unless this is wanted upstream of course.

**Comment by JohannesLichtenberger** [comment]
Of course, that would be great :-)

**Comment by EmilGedda** [comment]
Excellent, I'll fix the formatting issues to comply with upstream (2 spaces indent) and rebase away my "Fixes #16" in the commit message tomorrow.

**Comment by JohannesLichtenberger** [comment]
I think something failed in the integartion tests, but we'll see. Will merge tonight if no test failures occur. Otherwise, very cool :-)

BTW: Is this a university course (out of curiosity)?

**Comment by EmilGedda** [comment]
> I think something failed in the integartion tests, but we'll see. Will merge tonight if no test failures occur. Otherwise, very cool :-)
> 
> BTW: Is this a university course (out of curiosity)?

Might be because I closed the PR before the tests had cloned the repository maybe?

And yep this is part of a university course at KTH in Sweden, more specifically [DD2480 Software Engineering Fundamental](https://www.kth.se/student/kurser/kurs/DD2480?l=en). Our assignment links to [MunGell/awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners) which refers to this repo.

Our current assignment is to refactor 10 functions to reduce the cyclomatic complexity of them. This also includes adding some basic tests to increase the test coverage of the refactored functions. [Here are the tests I wrote for this refactor](https://github.com/soffan20/sirix/pull/18/commits/dfef442abee07016a5c4b7df1c50be621f971048), not very extensive, but passes our assignment criteria nonetheless. If you want the tests as well I can cherry pick them into this PR.

Now since this is a university course the requirements on simply lowering the cyclomatic complexity might not directly make the code better, [for instance this commit](https://github.com/soffan20/sirix/commit/cd6025deb64618f931a0a2fa708b8dfb865e1fa4), since it depends more on personal style. If you'd like I can upstream those changes as well.

We might have a couple more refactoring PRs coming the next 7 days if we deem them to be good enough for upstream.

**Comment by EmilGedda** [comment]
The PR has been formatted to match upstream's style. The cyclomatic complexity was reduced from 18 to 2.

**Comment by JohannesLichtenberger** [comment]
It's my primary goal to increase the test coverage considerably :-)

That's amazing, great course and thanks for the work.

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @EmilGedda for code

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @EmilGedda for code

**Pull request merged**
