### PR TITLE
Fix contributors anchor links in readme

### PR DESCRIPTION
**Pull request by cxong**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
What is this dash supposed to do?

**Comment by cxong** [comment]
Check the current readme and the fixed one - the current one will not scroll the page to the bookmarks; the fixed one will

**Comment by cxong** [comment]
The anchors are auto generated from the markdown headings, but because this heading contains a space (before the emoji), the spaces are converted to `-`.

**Comment by JohannesLichtenberger** [comment]
Ah, thanks :-)

**Pull request merged**
