### PR TITLE
Made changes in order to check if user already exists in keycloak script

### PR DESCRIPTION
**Pull request by MariannaDima**
Refined `add-user-keycloak.sh` script to include functionality for verifying user existence in Keycloak before proceeding with user addition. This update ensures appropriate messages are displayed based on different scenarios encountered during user checks.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Thanks a lot, looking forward to more contributions :-)

**Comment by JohannesLichtenberger** [comment]
@MariannaDima, can you try to update Keycloak to the newest version (I think startup scripts are, for instance, not supported anymore out of the box).

**Comment by MariannaDima** [comment]
Hello, do you mean issue 711? I will try to update Keycloak to the latest version and make the necessary changes if needed.

**Comment by JohannesLichtenberger** [comment]
Cool, thanks. Yes, currently our github action runningvthe tests fails, because there's an issue with the old image format of the keycloak 7.0.1 image. Finally time to upgrade ;-)

**Comment by JohannesLichtenberger** [comment]
@MariannaDima do you still have time?

**Comment by MariannaDima** [comment]
Hey, it's my finals period tbh so I haven't had the time yet. Give me one more week if possible to see if I can update it.

**Comment by JohannesLichtenberger** [comment]
@MariannaDima Good luck with the exams :-)

**Pull request merged**
