### PR TITLE
Extract common transaction logic into AbstractNodeTrxImpl

### PR DESCRIPTION
**Pull request by JPDSousa**

### CODE REVIEW

**Comment by JPDSousa** [comment]
@JohannesLichtenberger this is 90% complete. I need to fix some stuff (probably tests will break), but at least the gist of it is there. This is still code that was extracted from #410 (I excluded everything that was async commit related from that PR)

**Comment by JohannesLichtenberger** [comment]
Thanks a lot... I had a quick look and of course it makes a lot of sense :+1:

**Comment by JPDSousa** [comment]
It should be good to go now @JohannesLichtenberger 👍

**Comment by JohannesLichtenberger** [comment]
Yes, thanks a lot.

**Pull request merged**
