### PR TITLE
fix docker config for keycloak - issue#707

### PR DESCRIPTION
**Pull request by Stredsto**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Can you check why it fails?

**Comment by Stredsto** [comment]
sorry @JohannesLichtenberger , didnt get any time this week, will be looking this today and try to wrap it up.

**Comment by JohannesLichtenberger** [comment]
I guess the container is either not properly starting or stopping, but I'm currently using my phone and getting to the bottom of the log is cumbersome ;)

**Comment by JohannesLichtenberger** [comment]
@Stredsto any news? :)

**Comment by Stredsto** [comment]
> @Stredsto any news? :)

actually still looking through it, I'm not quite getting the actual reason for this to fail, 

the errors in logs are : 

```
2024-04-09T18:45:13.535+0000 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: /home/runner/work/sirix/sirix/bundles/sirix-core/src/test/java/io/sirix/service/json/shredder/JsonShredderTest.java uses preview features of Java SE 21.
Error: -09T18:45:15.929+0000 [ERROR] [system.err] Note: Recompile with -Xlint:preview for details.
2024-04-09T18:45:15.991+0000 [INFO] [org.gradle.api.internal.tasks.compile.incremental.recomp.CurrentCompilationAccess] Class dependency analysis for incremental compilation took 0.057 secs.
```

but also these starting from 37962 : 

```
2024-04-09T18:45:04.661+0000 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/usr/lib/jvm/temurin-21-jdk-amd64/bin/javadoc''
Error: -09T18:45:07.062+0000 [ERROR] [system.err] /home/runner/work/sirix/sirix/bundles/sirix-core/src/main/java/io/sirix/io/directio/FileChannelStorage.java:4: warning: ExtendedOpenOption is internal proprietary API and may be removed in a future release
Error: -09T18:45:07.062+0000 [ERROR] [system.err] import com.sun.nio.file.ExtendedOpenOption;
Error: -09T18:45:07.063+0000 [ERROR] [system.err]                        ^
Error: -09T18:45:07.546+0000 [ERROR] [system.err] /home/runner/work/sirix/sirix/bundles/sirix-core/src/main/java/io/sirix/access/SubComponentResourceSessionFactory.java:17: warning: no @param for <B>
Error: -09T18:45:07.547+0000 [ERROR] [system.err] public class SubComponentResourceSessionFactory<B extends GenericResourceSessionComponent.Builder<B, R, ?>, R extends ResourceSession<? extends NodeReadOnlyTrx, ? extends NodeTrx>>
Error: -09T18:45:07.547+0000 [ERROR] [system.err]        ^
```


maybe java version is conflicting ?

**Comment by JohannesLichtenberger** [comment]
Not sure what's going on here, tbh

**Pull request closed without merging**
