### PR TITLE
upgrade to vertx 4.0.0

### PR DESCRIPTION
**Pull request by mosheduminer**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Can you merge my latest changes (meaning fixed test failures)? :-) then I could add the PR already

**Comment by mosheduminer** [comment]
I actually merged those a couple days ago, once the tests passed. But since I replaced the isAuthorizedAwait function, the client is always rejected as unauthorized (hence, the tests always fail locally). I have tried to fix it, but have not yet succeeded.

**Comment by JohannesLichtenberger** [comment]
Ah, thought that's only the problem, when you want to remove the deprecation stuff.

**Comment by mosheduminer** [comment]
It appears that further work needs to be done (to resolve file conflicts).

**Comment by mosheduminer** [comment]
@JohannesLichtenberger the only remaining failing test appears to be
```
Integration test > Testing insert, then update, then query, then delete FAILED
    org.json.JSONException: Unparsable JSON string: Failure calling the RESTful API: org.sirix.exception.SirixIOException: java.io.FileNotFoundException: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/dbsetting.obj (No such file or directory)
```
I'm not sure why this is happening, I only modified code in the rest api.

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @mosheduminer for code

**Pull request merged**
