### PR TITLE
fixed some sonar issues #440

### PR DESCRIPTION
**Pull request by gvdutra**

### CODE REVIEW

**Comment by gvdutra** [comment]
Unparsable JSON string: Failure calling the RESTful API: java.lang.IllegalStateException: Transaction is already closed. maybe it is because of the "Thread.currentThread().interrupt();" that I added it. I will try to setup the integration tests on my local and go from there.

**Comment by JohannesLichtenberger** [comment]
I'm not sure why it fails, but you should be able to run the tests simply via gradle. It spans a Keycloak docker container and runs the tests. I'll have to clean up the tests and the whole HTTP-server sometime (mainly getting rid of the copy&paste stuff between XML and JSON databases and provide a test setup function).

**Comment by JohannesLichtenberger** [comment]
Sorry for all the trouble, but can you pull my latest changes I pushed a few minutes ago, too? :+1:

**Comment by gvdutra** [comment]
can you please try to run the pipeline again? Thank you.

**Comment by JohannesLichtenberger** [comment]
Done, but still failing. I also think that this thread interrupt stuff isn't right

**Comment by JohannesLichtenberger** [comment]
Do you still have time to work on this PR? :-)

**Comment by gvdutra** [comment]
Yes sorry, I was away for the holidays! https://github.com/sirixdb/sirix/pull/462 I will continue on this new one, I will be doing in several PR's to avoid the same issue on this one.

**Pull request closed without merging**
