### PR TITLE
Update to JDK 16

### PR DESCRIPTION
**Pull request by mosheduminer**
This first requires a new release of brackit, for JDK 16. @JohannesLichtenberger please review.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Can you make a OR for Brackit, too? ;-)

**Comment by mosheduminer** [comment]
Here https://github.com/sirixdb/brackit/pull/11 🙂.

**Comment by mosheduminer** [comment]
It seems like the brackit update wasn't published? Do we need a version bump?

**Comment by JohannesLichtenberger** [comment]
There are sadly other changes to consider:

org.sirix.diff.algorithm.FMSETest > testAllEigth FAILED
    java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(VarHandle,MemorySegment,long,int)void to (VarHandle,MemoryAddress,int)void
        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
        at org.sirix.io.memorymapped.MMFileWriter.write(MMFileWriter.java:188)

I guess something else changed in the foreign memory API.

**Comment by mosheduminer** [comment]
Oh, I seemed to have missed that. I'll look into it.

**Comment by mosheduminer** [comment]
It is very strange, because the tests pass locally (except two json shredder tests, which seems to have encoding issues, maybe windows related?).

**Comment by JohannesLichtenberger** [comment]
Maybe this helps: https://openjdk.java.net/jeps/393

Something clearly changed with method handles, regarding the exception.

Locally you run Windows, right? On Windows the file backend is used instead of the memory mapped backend ;-)

**Comment by mosheduminer** [comment]
> Locally you run Windows, right? On Windows the file backend is used instead of the memory mapped backend ;-)

Oh, of course 😅. I completely forgot. I'll try to fix the changes.

**Pull request closed without merging**
