### PR TITLE
Cleaned up code

### PR DESCRIPTION
**Pull request by FultonBrowne**
Removed unnecessary imports and thrown exceptions.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Do you know why a test fails?

[ERROR] Tests run: 429, Failures: 1, Errors: 0, Skipped: 46, Time elapsed: 183.985 s <<< FAILURE! - in TestSuite
[ERROR] testSheets on testSheets(org.sirix.diff.algorithm.FMSETest)(org.sirix.diff.algorithm.FMSETest)  Time elapsed: 1.9 s  <<< FAILURE!
org.xml.sax.SAXParseException: Element type "worksheet" must be followed by either attribute specifications, ">" or "/>".
	at org.sirix.diff.algorithm.FMSETest.test(FMSETest.java:270)
	at org.sirix.diff.algorithm.FMSETest.testSheets(FMSETest.java:208)

**Comment by FultonBrowne** [comment]
I thought it could have been when I removed some exceptions, but as you can see that did not work. I traced the error through every file referenced by that bit of code and I edited none of them, maybe there is a problem with the data set?

**Comment by JohannesLichtenberger** [comment]
Straneg, have to check out your code branch tomorrow or more likely next week. Do you get the same exception locally?

**Comment by FultonBrowne** [comment]
It builds locally, how do you run the test?

**Comment by JohannesLichtenberger** [comment]
Travis uses `mvn -q clean verify -B -U`

**Comment by FultonBrowne** [comment]
got it (sorry don't have much maven experience).

**Comment by FultonBrowne** [comment]
Its working on machine.

**Comment by JohannesLichtenberger** [comment]
Strange thing... will have to look at this on monday.

**Pull request closed without merging**
