### PR TITLE
Updated java version to 13 and maven to 3.6.2

### PR DESCRIPTION
**Pull request by Loniks**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Hmmm, what's going on with Travis? Why is it trying to make a Gradle build? :(

**Comment by Loniks** [comment]
It's a good question. As you can see I haven't added it at all

**Comment by JohannesLichtenberger** [comment]
Super strange thing, maybe can you try to temporarilly remove at least the Gradle wrapper then? :-) That said, I currently have no clue what Travis is doing here.

**Comment by Loniks** [comment]
Hi @JohannesLichtenberger Please see https://travis-ci.org/sirixdb/sirix/builds/594534626 This is build of previous P/R. Line 482 is `./gradlew assemble` This means that before my changes there was running of Gradle wrapper. I will try to figure out why it happens.

**Comment by JohannesLichtenberger** [comment]
I see... I guess the Gradle wrapper does not support Java 13... maybe there's a new version? However, still strange that it's invoked at all from Travis. I mean it's nowhere mentioned in the yml file...

**Comment by JohannesLichtenberger** [comment]
Hmmm, do your tests run locally? I'm not entirely sure but maybe a database doesn't get removed somewhere somehow (mismatch between JSON and XML document root nodes).

**Comment by Loniks** [comment]
It's a second strange thing. As you see https://github.com/Loniks/sirix/commit/1c90c9407ce20e87bd716a610da35a142c5c87e8/checks?check_suite_id=255017918 Github Actions same on local env don't find any test issue

**Comment by JohannesLichtenberger** [comment]
Yes, must be something Travis related, too :(

**Comment by JohannesLichtenberger** [comment]
I have to say I hate these issues, because it's so hard to debug what's really going on in Maven, Gradle, Jenkins/Travis, whatever...

**Comment by Loniks** [comment]
Ok, this issue is reproducible in Travis. It's time to to think why.

**Comment by JohannesLichtenberger** [comment]
Yes, I've also cleared the Travis caches... but it still failed.

**Comment by JohannesLichtenberger** [comment]
Great, now I'm getting the same test failures in the main branch after changing minor stuff in the Dockerfile, which is also broken I guess (even after reverting the changes) :-/ strange thing

**Comment by JohannesLichtenberger** [comment]
I've also removed the Gradle stuff for now... still not working (also not in our main branch) :(

**Comment by JohannesLichtenberger** [comment]
In my IDE and via maven it's for sure also running all the tests fine, locally.

**Comment by JohannesLichtenberger** [comment]
Fixed :-) can you update your branch and the PR? Then I can accept I guess :-)

**Comment by Loniks** [comment]
Hi @JohannesLichtenberger Just pull your changes and logs like we have the green light to marge it

**Comment by JohannesLichtenberger** [comment]
Very cool, thank you so much for all your effort. Hope you give SirixDB a try :+1:

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @Loniks for code

**Pull request merged**
