### PR TITLE
252 create a kotlin cli

### PR DESCRIPTION
**Pull request by ManfredNentwig**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Thanks a lot, that's a bunch if work you've done :)

**Comment by JohannesLichtenberger** [comment]
@all-contributors please add @ManfredNentwig for code

**Comment by JohannesLichtenberger** [comment]
Maybe we can extract some classes you're using from the rest-api module into a sirix-kotlin-common module/bundle :-)

**Comment by ManfredNentwig** [comment]
Thank you for merging.

I would really prever to have a  common module or to implement something like a high level api wich are used by REST and CLI.
God luck with your debug session!

**Pull request merged**
