### PR TITLE
Replace JSR-305 for checkerframework on sirix-core #467

### PR DESCRIPTION
**Pull request by gvdutra**

### CODE REVIEW

**Comment by gvdutra** [comment]
As I am having some issues with replacing it completely, I am breaking down the PR for every sirix sub-project to be on the "safe" side.

**Comment by JPDSousa** [comment]
@gvdutra I think this is one of those PRs where a description is of upmost important? Why are we replacing javax by a third library? Can you include some links that point out to this being a good practice?

From a code standpoint, this looks awesome as usual 👌

**Comment by gvdutra** [comment]
Hi Joao! Oops ... sorry, I thought as it was linked with the issue it would be ok to leave without a description! I will put it from now on!

I was initially about to replace findbugs, which is dead project to spotbugs. However, I found out that Sirix is only using it because of JSR-305, so that searching more I found out that JSR-305 is also dead! After searching and searching, I found out this third party project, that is like a interface with implementation for all those static validation in the market.  https://checkerframework.org/manual/#faq-jsr-305

https://jcp.org/en/jsr/detail?id=305 -> Status: [Dormant](https://jcp.org/en/introduction/glossary#status)

https://github.com/sirixdb/sirix/issues/467#issuecomment-1038628300


Please, if you think this is not a good idea feel free to decline the PR, no worries at all!

Many thanks!

**Comment by JohannesLichtenberger** [comment]
I think it's okay to switch and we are then probably able to really check the code at compile time as far as I understand!?

What do you think @JPDSousa? If you have no objections I'd otherwise merge the changes!?

@gvdutra thanks for all your work. If you'd like to work on features at some point or other refactoring stuff keep up the great work and let me know :+1:

**Review by JPDSousa — APPROVED** [review]

**Comment by JPDSousa** [comment]
> Hi Joao! Oops ... sorry, I thought as it was linked with the issue it would be ok to leave without a description! I will put it from now on!
> 
> I was initially about to replace findbugs, which is dead project to spotbugs. However, I found out that Sirix is only using it because of JSR-305, so that searching more I found out that JSR-305 is also dead! After searching and searching, I found out this third party project, that is like a interface with implementation for all those static validation in the market. https://checkerframework.org/manual/#faq-jsr-305
> 
> https://jcp.org/en/jsr/detail?id=305 -> Status: [Dormant](https://jcp.org/en/introduction/glossary#status)
> 
> [#467 (comment)](https://github.com/sirixdb/sirix/issues/467#issuecomment-1038628300)
> 
> Please, if you think this is not a good idea feel free to decline the PR, no worries at all!
> 
> Many thanks!

Sorry @gvdutra I was reviewing this on my phone, and I missed the issue link on the commit title. The usual convention is to include a keyword and the issue id in the PR description (e.g., `Closes #467`). You can read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Nevertheless my goal was more towards us making data driven decisions, but looking both at your comment (to which I'm replying) as well as the original issue, I see you've made an investigation and included links for us to understand the reasons behind the PR 🏆 

Once again, sorry for the confusion, and great work!!

**Pull request merged**
