### PR TITLE
enhancement: Automate Git hook setup for code formatting with Spotless

### PR DESCRIPTION
**Pull request by abhishekscte0327**
- Added githooks configuration to automate code formatting using Spotless.
- Ensured that the hooks are set up automatically when running `./gradlew` commands.
- This enhancement will help maintain consistent code formatting across the project.

This PR addresses issue <https://github.com/sirixdb/sirix/issues/465>.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
@abhishekscte0327 we should use this formatter: https://github.com/sirixdb/sirix/blob/main/SirixDB.xml

**Comment by abhishekscte0327** [comment]
Hii @JohannesLichtenberger, 
I've run into an issue with the provided SirixDB.xml file. It’s specific to IntelliJ IDEA and isn’t compatible with tools like Spotless or Checkstyle, which are cross-IDE friendly. Translating the provided xmlinto a format like Eclipse or Checkstyle is possible but not all rules can be perfectly mapped.

Would you prefer we go with an IntelliJ-specific solution, or should we explore a cross-IDE approach? I'm open to suggestions if you have any other ideas.

**Comment by JohannesLichtenberger** [comment]
IIRC, the file was exported from Eclipse originally; maybe you can trace it back :-) That said, maybe we can otherwise go for an IntelliJ-specific solution, as reformatting almost everything, IMHO may not be worth it, as it also destroys history.

**Comment by abhishekscte0327** [comment]
I have observed that using IntelliJ-specific formatting also results in reformatting a large portion of the codebase. However, i successfully traced the XML file to its original Eclipse format.

We can proceed with a cross-IDE solution using Spotless with the Eclipse formatter.  Please note that this approach will still lead to significant reformatting of the codebase.

**As an alternative, i propose using a pre-commit hook that formats only the modified files. This solution minimizes disruption by incrementally applying formatting changes, preserving the commit history, and avoiding a single massive reformatting commit. Here’s a brief overview of the approach:**

**Pre-Commit Hook**: Formats only the files that are staged for commit.
**Gradual Formatting**: Ensures formatting is applied over time, reducing the impact on the codebase.
Please let me know if you’re comfortable with this approach or if you have any other suggestions.

**Comment by JohannesLichtenberger** [comment]
Sounds great, I'm not sure if it had "proper" formatting of streams back then, as I mostly prefer, when each function call is aligned on the next line, but maybe only if they wouldn't fit on one line.

Otherwise the approach sounds good :-)

**Comment by abhishekscte0327** [comment]
Thanks for your feedback!

Regarding the formatting of streams where each function call is aligned on the next line, we can customize the formatting rules to fit this preference. We can ensure that function calls are aligned properly, either fitting them on one line or aligning them on the next line when they don't fit.

I'll proceed with setting up the pre-commit hook and the cross-IDE formatting solution using Spotless with the Eclipse formatter. We can tweak the settings further if needed to match the preferred formatting style.

Please let me know if you have any specific formatting configurations in mind, and I'll incorporate them.

**Comment by JohannesLichtenberger** [comment]
This can be closed, right?

**Comment by abhishekscte0327** [comment]
yeah, i am closing it.

**Pull request closed without merging**
