### PR TITLE
organized sirixverticle apis by resource, then CRUD

### PR DESCRIPTION
**Pull request by JoelLau**

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Hi @JoelLau, can you fix the compile error and maybe try to run the integration tests?

**Comment by JohannesLichtenberger** [comment]
Hi Joel, are you still working on this? Would be great to be able to merge this :)

**Comment by JoelLau** [comment]
@JohannesLichtenberger sorry! work got a little hectic. I plan to work on it next week along with the other REST issue

**Comment by JohannesLichtenberger** [comment]
Ah cool, thank you :)

**Comment by JoelLau** [comment]
still looking into this ...

**Pull request closed without merging**
