### PR TITLE
Fix For issue #541

### PR DESCRIPTION
**Pull request by Aditya31398**
Issue #541
Added Check admin user exists before creating new admin user

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
I think the user is not created anymore (downloaded and checked the log): 

```
2022-11-05T14:14:08.6137375Z     14:14:08.594 [vert.x-eventloop-thread-1] TRACE io.vertx.ext.web.RoutingContext - Calling the  handler
2022-11-05T14:14:08.6137830Z 
2022-11-05T14:14:08.6138140Z Integration test > Testing a simple query to get the node-key of a node STANDARD_ERROR
2022-11-05T14:14:08.6138852Z     Exception in thread "vert.x-eventloop-thread-1 @coroutine#11" io.vertx.core.impl.NoStackTraceThrowable: invalid_grant: Invalid user credentials
```

**Comment by JohannesLichtenberger** [comment]
Would be awesome if you can fix this -- thanks so far for your effort :)

**Comment by JohannesLichtenberger** [comment]
@Aditya31398 still the same error, sadly

**Comment by Aditya31398** [comment]
When I try locally the kcadm.sh command gives out error connection refused. This is the problem. I'll try to fix it

**Comment by Aminmalek** [comment]
I had this issue just one time I think Its related to how docker save the credentials and why It just happen one time, I think you need to check the ENVs another time it seems both docker and the keycloak script attempts to save the user and they have conflicts with each other.

**Pull request closed without merging**
