### PR TITLE
Support for automated rest-api integration test - #128

### PR DESCRIPTION
**Pull request by balajiv113**
Automated Rest API Integration test using docker and gradle.

Before test docker-compose will be started and after test docker-compose will be shutdown

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Hm, we have to investigate what's going wrong especially with these two:

org.sirix.rest.SirixVerticleXmlTest > testGet(Vertx, VertxTestContext) FAILED

    java.util.concurrent.TimeoutException: The test execution timed out. Make sure your asynchronous code includes calls to either VertxTestContext#completeNow(), VertxTestContext#failNow() or Checkpoint#flag()

org.sirix.rest.SirixVerticleXmlTest > testPut(Vertx, VertxTestContext) FAILED

    java.util.concurrent.TimeoutException: The test execution timed out. Make sure your asynchronous code includes calls to either VertxTestContext#completeNow(), VertxTestContext#failNow() or Checkpoint#flag()

I think the other one needs a simple lexical sorting of database names first. Succeeded locally, but I guess it depends on the filesystem...

**Comment by balajiv113** [comment]
Ya agreed. Even the 1st 2 were successful in my local machine. All tests were successful locally.

**Comment by JohannesLichtenberger** [comment]
Yeah, for me too the last time I executed them... but I can only think that the directory listing might be different depending on the filesystem. So, sorting by directory name first will probably fix this one.

The other two, hmmm.

**Comment by balajiv113** [comment]
@JohannesLichtenberger 
I have fixed the JSON difference and also the timeout issue. The one new issue that is present is testDeleteResource which is giving 500 Internal Server error. That to in random not in all builds.

**Comment by JohannesLichtenberger** [comment]
If you disable the test, the other tests run every time without an assertion error? Hm, usually the exception should get printed, but I couldn't see anything. Maybe we can disable the test for now if it otherwise runs every time fine. I'd love to merge :-)

**Comment by JohannesLichtenberger** [comment]
So, the other tests were failing because Keycloak wasn't up, right?

**Comment by balajiv113** [comment]
Yes thats correct, the timeout exception were due to keycloak not fully up. To solve that i added custom health check in docker-compose.

**Comment by JohannesLichtenberger** [comment]
Ah cool. I just checked the code and I couldn't see an obvious bug when a resource in a database should be deleted, hmm. That said, I think sometimes the exceptions don't pop up...

**Comment by balajiv113** [comment]
As you could see, in travis this time that testDeleteResource is successful. May be will check for one more build if it fails again will disable it for now and analyse it further.

**Comment by JohannesLichtenberger** [comment]
Hm, probably we can also increase the timeout in the health check. I think the Keycloak start is rather slow.

**Comment by JohannesLichtenberger** [comment]
Damn, still fails

**Comment by balajiv113** [comment]
Ahh ya. In my local system its not failing if that fails then can debug easily and fix it.

**Comment by JohannesLichtenberger** [comment]
Same here, not failing locally. But it would be easy to fix if we get the stacktrace, hmm.

**Comment by JohannesLichtenberger** [comment]
I think my Vert.x error handling is not always right, somehow...

**Comment by JohannesLichtenberger** [comment]
I think at first delete(...) has to be called before each test and after each test to cleanup stuff. I'm not sure what's now failing, though.

**Comment by balajiv113** [comment]
@JohannesLichtenberger Looks like in travis we need to disable docker deploy for pull requests

**Comment by balajiv113** [comment]
> I think at first delete(...) has to be called before each test and after each test to cleanup stuff. I'm not sure what's now failing, though.

No i tried with that, delete actually deletes the HTTP server started by vertx for testing so we will be getting connection refused for all the test cases

**Comment by JohannesLichtenberger** [comment]
> @JohannesLichtenberger Looks like in travis we need to disable docker deploy for pull requests

Yes, absolutely

**Comment by JohannesLichtenberger** [comment]
> > I think at first delete(...) has to be called before each test and after each test to cleanup stuff. I'm not sure what's now failing, though.
> 
> No i tried with that, delete actually deletes the HTTP server started by vertx for testing so we will be getting connection refused for all the test cases

Yes, saw this happening. I disabled the test for now and I'm going to merge. I hope we'll figure out why the test fails on Travis.

**Pull request merged**
